# Generated by Django 5.2.1 on 2025-05-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la alergia')),
                ('severity', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=10, verbose_name='Severidad')),
                ('common_reactions', models.TextField(verbose_name='Reacciones comunes')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, help_text='Seleccione las alergias conocidas del paciente', to='core.allergy', verbose_name='Alergias'),
        ),
    ]
